apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgACQkWUqw9N2iJn3UD7YjN7iun4jS44HQRjnF2z6wLtDFQodk8RSh/ZEYQWCYKt1lLpnrSixizh8IIUU1iye1xTP62XYaN8QsMVb7kfmlzsMOAxJqiNFOHNWCrFo7T3k+elfyvgoTNt2H0vR57VGidohqJLfjY6XKHI7OoP/d8q9M2zQpUci8nkKQhAy5g+EwrCalsUd1/IV6gVuGOSbe2Pg19xEdKXDV5LHUW4ZDNC/j5ke+BJxlS3txp8z3j3nMwXu2S6Qw36TaSvobEt+NnjxHnGay1CANI9tcmfvwxc95kojq28afs0HM3GVpgBQbkevKoQerYNQtL7LzS2RrUwWpwBMIyEVBqWUEHoY5JKSCS1jIvkTwQAdYdHyShANQjNFNbXE/8x0EQ5gv7GVxf3DU8IvwGXVoPv/YfgKGybUuR8f2IMDJW4D8CgnORz8ZSmpf0PHEFSnwmfw8hh/GZHzpunZkpLF0JI7G+jxtOSv5rVhGZ5llcUZE09k8t7ZscNkSIB+AeObEmVOJRSw5kstvCDK8HPCWPQ1fJg7JddMDzooW1Xw4BllIycvVssc9uQOqO1dBDlc0WoEUeXjWeyp1OP+R9r6/8Ma/hOH+RNmEWS2jfcBxGt3FSFNNn2xbWxGvrmRux9kG5go1zcP23HFFr7Y3Q8RPxS6WpVy2IYtSegF4wDN6ViKMsOrgkNIYGBIUuG2qFwqUC7/IdGcF7lSbRHD3RzTv1Yw49ECjqULFI/QmlcJCdb
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

